### ISSUE TITLE
This skeleton is bust, causes Packager to Fail

### ISSUE THREAD

**Issue by XenitXTD** [Jeroen-G/packager-skeleton#13]
Title Says it all and it effectively breaks the Packager

**Comment by Jeroen-G** [comment]
What's the error?

**Comment by XenitXTD** [comment]
> What's the error?

Hi, 

So at time of writing

I perform a clean setup with "Laravel New Project" which sets up a new laravel 8.0.3 project

then I pull in your package with "composer require jeroen-g/laravel-packager"

once its installed I attempt to perform the "php artisan packager:new ACME ABC"

At the first step I see the following

```
0/6 [>---------------------------]   0% Creating package ACME\ABC...
Creating packages directory...
Creating vendor...
Downloading skeleton...

   ErrorException

  rename(/home/vagrant/Code/_packages/package_test/packages/ACME/ABC/src/MyPackage.php,/home/vagrant/Code/_packages/package_test/packages/ACME/ABC/src/ABC.php): No such file or directory

  at vendor/jeroen-g/laravel-packager/src/FileHandler.php:184
    180▕         ] : $manifest;
    181▕
    182▕         foreach ($rewrites as $file => $name) {
    183▕             $filename = str_replace($bindings[0], $bindings[1], $name);
  ➜ 184▕             rename($this->packagePath().'/'.$file, $this->packagePath().'/'.$filename);
    185▕         }
    186▕     }
    187▕
    188▕     /**

      +16 vendor frames
  17  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
```

Looking in the packages directory I can see the ACME/ABC folder with what appears to be the skeleton source but it was never renamed etc.

This is a clean project, came here from reference on Laracasts and my experience has had no success with this package or skeleton

**Comment by Jeroen-G** [comment]
Thank you, now I can look into it!

**Comment by Jeroen-G** [comment]
On the latest release I was not able to reproduce it. Please try again!

**Comment by karmendra** [comment]
I am having laravel 8.20.1 installed with jeroen-g/laravel-packager v2.6 all this running on php 7.4.10 (on Homestead)

When I run php artisan packager:new foo/bar

I see it creates the boilerplate packages/foo/bar

but the files are not renamed as required.

Further investigation revealed that this code  in `public function renameFiles` 

        $files = new RecursiveDirectoryIterator($this->packagePath());
        foreach (new RecursiveIteratorIterator($files) as $file) {
        
Is causing the issue, the thing is `RecursiveDirectoryIterator` is not going inside the src and config folders thus is never picks the files inside those folder for renaming.

So I think problem is not this `packager-skeleton` but the  `laravel-packager`

Can you please check?

Update:
--------
Still further when I investigate, I figured there is no files in src folder when the RecursiveDirectoryIterator instance is created when it is running.

Instead of `$this->packagePath()` if I hardcode a directory path in `new RecursiveDirectoryIterator($this->packagePath());` everything works fine.

**Comment by Jeroen-G** [comment]
That is very precise information and something I can work with, thank you. If you happen to find the solution, don't hesitate to open a PR!

**Comment by bilogic** [comment]
https://github.com/Jeroen-G/laravel-packager/issues/101
Could this be due to the VirtualBox issue?

@Jeroen-G I'm facing it again, going to try and get to the root this time.

**Comment by XenitXTD** [comment]
Hey there back again, 

So I ran into this issue again and I was using a VM in this case homestead. 

Looking at other user feedback and @bilogic link to a similar ticket this is actually a timing issue

so in my case I just went into the 

[Packager:New File](https://github.com/Jeroen-G/laravel-packager/blob/master/src/Commands/NewPackage.php)

and just put a delay between the retrieval of the archive/extraction and the rename step

This could be a mix of several factors, system extract performance and file system speed on mount etc and the step may just be one step to fast and execute before the files are there to be renamed.

so I just added a sleep(2); to just give a bit of a delay

I will add that I tried this on the system directly and it worked no issue but the virtual environment was a permanent issue.

below is the adjustment I made just to get this working for me.

``` php
$manifest = (file_exists($this->conveyor->packagePath().'/rewriteRules.php')) ? $this->conveyor->packagePath().'/rewriteRules.php' : null;
        
sleep(2);
        
$this->conveyor->renameFiles($manifest);
```
